### ISSUE TITLE
win10机器上，python3.7，pip安装失败，报编码错误

### ISSUE THREAD

**Issue by longweiqiang** [huanghyw/concurrent_log#1]
如截图所示：
![image](https://user-images.githubusercontent.com/22344864/71573723-41bbdc80-2b20-11ea-8e95-e1546bff8265.png)

**Comment by longweiqiang** [comment]
我本地修改`setup.py`文件如下，安装成功
```python
with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()
```

**Comment by huanghyw** [comment]
确实需要指定编码，这个地方遗漏了，我发个版本修复下，多谢提出

**Comment by longweiqiang** [comment]
不客气，应该做的。能用起来就好，最近被这个多进程打印日志搞的头大

**Comment by huanghyw** [comment]
> 不客气，应该做的。能用起来就好，最近被这个多进程打印日志搞的头大

我也是遇到了这个问题，又不想搞那种socket、queue的方式，感觉有点重，所以参考了一些其他人的实现方案，基于标准库做了这个小封装

**Comment by huanghyw** [comment]
已发布小版本1.0.1对该问题进行了修复

**Comment by longweiqiang** [comment]
thx
