### ISSUE TITLE
你好！测试PermissionError

### ISSUE THREAD

**Issue by zhongsdjn** [huanghyw/concurrent_log#4]
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Administrator\\Desktop\\AAA\\Django3_Test\\logs\\test.log' -> 'C:\\Users\\Administrator\\Desktop\\AAA\\Django3_Test\\logs\\test.log.2020-07-02_11-28-26'
Call stack:

环境：win10 Pycharm Django3.0 Python3.7.2
加上--noreload没问题  不过不就是单进程线程了吗

**Comment by huanghyw** [comment]
我刚才测试了下，新建了一个干净的django项目，加了个hello路径。在mac环境测试没问题，代码我上传到附件了。我这没有windows，您下来代码在windows下试试看。
[djangotest.zip](https://github.com/huanghyw/concurrent_log/files/4861939/djangotest.zip)

**Comment by zhongsdjn** [comment]
这个问题之前遇到过，似乎和django启动的配置有关  自己实现的log方法和网上的几个方法也会遇到  网上随便找了篇博客           https://www.jianshu.com/p/8e3eef392f92  
还有就是在terminal启动不会有  应该是因为在配置文件settings.py中配置的原因


| |
zhongsdjn
|
|
zhongsdjn@163.com
|
签名由网易邮箱大师定制
在2020年7月2日 12:20，红头土豆<notifications@github.com> 写道：

我刚才测试了下，新建了一个干净的django项目，加了个hello路径。在mac环境测试没问题，代码我上传到附件了。我这没有windows，您下来代码在windows下试试看。
djangotest.zip

**Comment by zhongsdjn** [comment]
我要在Centos系统离线安装这个包 下载的源码解压后执行pip setup.py install 报错  有遇到吗？




/usr/local/python3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing src/concurrent_log.egg-info/PKG-INFO
writing dependency_links to src/concurrent_log.egg-info/dependency_links.txt
writing requirements to src/concurrent_log.egg-info/requires.txt
writing top-level names to src/concurrent_log.egg-info/top_level.txt
reading manifest file 'src/concurrent_log.egg-info/SOURCES.txt'
writing manifest file 'src/concurrent_log.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying src/concurrent_log.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    python_requires='>=3.6',
  File "/usr/local/python3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/python3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/python3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/python3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/python3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/root/.virtualenvs/django_test/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)








| |
zhongsdjn
|
|
zhongsdjn@163.com
|
签名由网易邮箱大师定制
在2020年7月2日 13:47，zhongsdjn<zhongsdjn@163.com> 写道：
这个问题之前遇到过，似乎和django启动的配置有关  自己实现的log方法和网上的几个方法也会遇到  网上随便找了篇博客           https://www.jianshu.com/p/8e3eef392f92  
还有就是在terminal启动不会有  应该是因为在配置文件settings.py中配置的原因


| |
zhongsdjn
|
|
zhongsdjn@163.com
|
签名由网易邮箱大师定制
在2020年7月2日 12:20，红头土豆<notifications@github.com> 写道：

我刚才测试了下，新建了一个干净的django项目，加了个hello路径。在mac环境测试没问题，代码我上传到附件了。我这没有windows，您下来代码在windows下试试看。
djangotest.zip

**Comment by huanghyw** [comment]
我这试了下，离线安装也是可以的……
```
(concurrent_log) ➜  concurrent_log git:(master) python setup.py install
running install
running bdist_egg
running egg_info
creating src/concurrent_log.egg-info
writing src/concurrent_log.egg-info/PKG-INFO
writing dependency_links to src/concurrent_log.egg-info/dependency_links.txt
writing requirements to src/concurrent_log.egg-info/requires.txt
writing top-level names to src/concurrent_log.egg-info/top_level.txt
writing manifest file 'src/concurrent_log.egg-info/SOURCES.txt'
reading manifest file 'src/concurrent_log.egg-info/SOURCES.txt'
writing manifest file 'src/concurrent_log.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/concurrent_log
copying src/concurrent_log/__init__.py -> build/lib/concurrent_log
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/concurrent_log
copying build/lib/concurrent_log/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/concurrent_log
byte-compiling build/bdist.macosx-10.9-x86_64/egg/concurrent_log/__init__.py to __init__.cpython-37.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying src/concurrent_log.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/concurrent_log-1.0.1-py3.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing concurrent_log-1.0.1-py3.7.egg
Copying concurrent_log-1.0.1-py3.7.egg to /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages
Adding concurrent-log 1.0.1 to easy-install.pth file

Installed /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages/concurrent_log-1.0.1-py3.7.egg
Processing dependencies for concurrent-log==1.0.1
Searching for portalocker==1.5.2
Best match: portalocker 1.5.2
Adding portalocker 1.5.2 to easy-install.pth file

Using /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages
Finished processing dependencies for concurrent-log==1.0.1

```

**Comment by zhongsdjn** [comment]
pip install .  可以
python setup.py install 不行  
Centos7.8 python3.7.2


| |
zhongsdjn
|
|
zhongsdjn@163.com
|
签名由网易邮箱大师定制
在2020年7月2日 14:26，红头土豆<notifications@github.com> 写道：

我这试了下，离线安装也是可以的……

(concurrent_log) ➜  concurrent_log git:(master) python setup.py install

running install

running bdist_egg

running egg_info

creating src/concurrent_log.egg-info

writing src/concurrent_log.egg-info/PKG-INFO

writing dependency_links to src/concurrent_log.egg-info/dependency_links.txt

writing requirements to src/concurrent_log.egg-info/requires.txt

writing top-level names to src/concurrent_log.egg-info/top_level.txt

writing manifest file 'src/concurrent_log.egg-info/SOURCES.txt'

reading manifest file 'src/concurrent_log.egg-info/SOURCES.txt'

writing manifest file 'src/concurrent_log.egg-info/SOURCES.txt'

installing library code to build/bdist.macosx-10.9-x86_64/egg

running install_lib

running build_py

creating build

creating build/lib

creating build/lib/concurrent_log

copying src/concurrent_log/__init__.py -> build/lib/concurrent_log

creating build/bdist.macosx-10.9-x86_64

creating build/bdist.macosx-10.9-x86_64/egg

creating build/bdist.macosx-10.9-x86_64/egg/concurrent_log

copying build/lib/concurrent_log/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/concurrent_log

byte-compiling build/bdist.macosx-10.9-x86_64/egg/concurrent_log/__init__.py to __init__.cpython-37.pyc

creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying src/concurrent_log.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying src/concurrent_log.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying src/concurrent_log.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying src/concurrent_log.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

copying src/concurrent_log.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO

zip_safe flag not set; analyzing archive contents...

creating dist

creating 'dist/concurrent_log-1.0.1-py3.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it

removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)

Processing concurrent_log-1.0.1-py3.7.egg

Copying concurrent_log-1.0.1-py3.7.egg to /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages

Adding concurrent-log 1.0.1 to easy-install.pth file



Installed /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages/concurrent_log-1.0.1-py3.7.egg

Processing dependencies for concurrent-log==1.0.1

Searching for portalocker==1.5.2

Best match: portalocker 1.5.2

Adding portalocker 1.5.2 to easy-install.pth file



Using /opt/anaconda3/envs/concurrent_log/lib/python3.7/site-packages

Finished processing dependencies for concurrent-log==1.0.1
